### PR TITLE
Enhance overall test logic

### PR DESCRIPTION
**Pull request by BlaCkinkGJ**
## TODO

1. Add an integration test routine in the GitHub Actions.
2. Configure the test environments based on the arguments.

### CODE REVIEW

**Comment by BlaCkinkGJ** [comment]
I added the exit code in the cppcheck. By the way, currently, cppcheck has some issue that generates [false positive result on the memory leaks situations](https://cppcheck.sourceforge.io/forum/viewtopic.php?f=4&t=3).

**Comment by BlaCkinkGJ** [comment]
I am going to silent the cppcheck’s memleak checks. Alternatively, I will add lasan in the integration test.

**Comment by BlaCkinkGJ** [comment]
Becuase we already have integration test logic for this program, we just add compile flag to adopt `lasan` for `make integration-test`.

**Comment by BlaCkinkGJ** [comment]
It is good to use `leak-ignore` flag but we must ensure that flags exists or not.

**Comment by BlaCkinkGJ** [comment]
Just make it silent.

**Review by jsy0404 — APPROVED** [review]
doesn't seem to be any logic issues 👍

**Pull request merged**
